#spring.application.name=microservice-student

server:
  port: 8090

spring:
  application:
    name: msvc-student
    #-> ruta donde se encuentra el config server (lo coloco provicional para evitar errores)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDb
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#CONFIGURACION PARA QUE EL SERVICIO SE CONECTE CON EUREKA DE MANERA AUTOMATICA

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka